//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccWebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLog
    {
        public string FundNo { get; set; }
        public int OrderNo { get; set; }
        public string ProgramName { get; set; }
        public string TableName { get; set; }
        public string LogReason { get; set; }
        public string KeyFields { get; set; }
        public Nullable<int> TotalChangedFields { get; set; }
        public string ChangeContent { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogPerson { get; set; }
    }
}
