//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccWebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceSubject
    {
        public string FundNo { get; set; }
        public string AccYear { get; set; }
        public string SubNo { get; set; }
        public string SubName { get; set; }
        public string UsageFlag { get; set; }
        public string SubTypeNo { get; set; }
    }
}
