//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccWebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CombindUsageBudget
    {
        public string FundNo { get; set; }
        public string AccYear { get; set; }
        public int OrderNo { get; set; }
        public string SubNo { get; set; }
        public Nullable<long> CombindUsageAmount { get; set; }
        public Nullable<long> CombindUsageAmount_01 { get; set; }
        public Nullable<long> CombindUsageAmount_02 { get; set; }
        public Nullable<long> CombindUsageAmount_03 { get; set; }
        public Nullable<long> CombindUsageAmount_04 { get; set; }
        public Nullable<long> CombindUsageAmount_05 { get; set; }
        public Nullable<long> CombindUsageAmount_06 { get; set; }
        public Nullable<long> CombindUsageAmount_07 { get; set; }
        public Nullable<long> CombindUsageAmount_08 { get; set; }
        public Nullable<long> CombindUsageAmount_09 { get; set; }
        public Nullable<long> CombindUsageAmount_10 { get; set; }
        public Nullable<long> CombindUsageAmount_11 { get; set; }
        public Nullable<long> CombindUsageAmount_12 { get; set; }
    }
}
