//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccWebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSummary
    {
        public string FundNo { get; set; }
        public string AccYear { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> BudgetNum { get; set; }
        public Nullable<int> ActualNum { get; set; }
        public Nullable<int> CompareNum { get; set; }
        public string Statement { get; set; }
    }
}
