//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccWebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBCJSONRecord
    {
        public string 基金代碼 { get; set; }
        public string PFK_會計年度 { get; set; }
        public string PFK_動支編號 { get; set; }
        public string PFK_種類 { get; set; }
        public string PFK_次別 { get; set; }
        public string 傳票JSON1 { get; set; }
        public string 傳票JSON2 { get; set; }
        public string 是否結案 { get; set; }
    }
}
