//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccWebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBCRecord
    {
        public string FundNo { get; set; }
        public string AccYear { get; set; }
        public string PurchaseNo { get; set; }
        public string BudgetType { get; set; }
        public int Times { get; set; }
        public int DetailNo { get; set; }
        public string VoucherContent { get; set; }
        public Nullable<int> VoucherNum { get; set; }
        public string VouKind_1 { get; set; }
        public string VouKind_2 { get; set; }
        public Nullable<int> AccMainNo_1 { get; set; }
        public string VouNo_1 { get; set; }
        public Nullable<int> AccMainNo_2 { get; set; }
        public string VouNo_2 { get; set; }
        public Nullable<System.DateTime> VoucherCreateDate_1 { get; set; }
        public string VoucherCreatePerson_1 { get; set; }
        public Nullable<System.DateTime> VoucherCreateDate_2 { get; set; }
        public string VoucherCreatePerson_2 { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
