//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccWebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBCVisaDetailAbateDetail
    {
        public string 基金代碼 { get; set; }
        public string PK_會計年度 { get; set; }
        public string PK_動支編號 { get; set; }
        public string PK_種類 { get; set; }
        public string PK_次別 { get; set; }
        public string PK_明細號 { get; set; }
        public Nullable<decimal> F_核定金額 { get; set; }
        public string F_傳票年度 { get; set; }
        public string F_傳票號1 { get; set; }
        public Nullable<int> F_傳票明細號1 { get; set; }
        public string F_製票日期1 { get; set; }
        public string F_傳票號2 { get; set; }
        public Nullable<int> F_傳票明細號2 { get; set; }
        public string F_製票日期2 { get; set; }
        public string F_受款人 { get; set; }
        public string F_受款人編號 { get; set; }
        public string F_原動支編號 { get; set; }
    }
}
