//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccWebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanInfo
    {
        public string FundNo { get; set; }
        public string AccYear { get; set; }
        public int OrderNo { get; set; }
        public string ItemNo { get; set; }
        public string PlanName { get; set; }
        public string LoanYear { get; set; }
        public Nullable<long> LastRestAmount { get; set; }
        public Nullable<long> BudgetAmount { get; set; }
        public Nullable<long> ActualAmount { get; set; }
        public Nullable<long> BudgetDecreaseAmount { get; set; }
        public Nullable<long> ActualDecreaseAmount { get; set; }
        public Nullable<long> RestAmount { get; set; }
        public string Remark { get; set; }
        public string PlanKind { get; set; }
    }
}
