//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccWebService.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NPSFEntities : DbContext
    {
        public NPSFEntities()
            : base("name=NPSFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Accounts_Categories> Accounts_Categories { get; set; }
        public DbSet<Accounts_FundMgr> Accounts_FundMgr { get; set; }
        public DbSet<Accounts_PermissionCategories> Accounts_PermissionCategories { get; set; }
        public DbSet<Accounts_Permissions> Accounts_Permissions { get; set; }
        public DbSet<Accounts_RolePermissions> Accounts_RolePermissions { get; set; }
        public DbSet<Accounts_Roles> Accounts_Roles { get; set; }
        public DbSet<Accounts_TopBudgetUser> Accounts_TopBudgetUser { get; set; }
        public DbSet<Accounts_TopUser> Accounts_TopUser { get; set; }
        public DbSet<Accounts_UserLog> Accounts_UserLog { get; set; }
        public DbSet<Accounts_UserRoles> Accounts_UserRoles { get; set; }
        public DbSet<Accounts_Users> Accounts_Users { get; set; }
        public DbSet<AppLog> AppLog { get; set; }
        public DbSet<AppLogColumns> AppLogColumns { get; set; }
        public DbSet<BalanceSubject> BalanceSubject { get; set; }
        public DbSet<BankAccount> BankAccount { get; set; }
        public DbSet<BankInfo> BankInfo { get; set; }
        public DbSet<BudgetAccumulateMain> BudgetAccumulateMain { get; set; }
        public DbSet<BudgetAccumulateReport> BudgetAccumulateReport { get; set; }
        public DbSet<BudgetInfoNBA> BudgetInfoNBA { get; set; }
        public DbSet<BudgetReportCloseRecord> BudgetReportCloseRecord { get; set; }
        public DbSet<BudgetReportRecord> BudgetReportRecord { get; set; }
        public DbSet<BudgetSettingPeriod> BudgetSettingPeriod { get; set; }
        public DbSet<BudgetSummaryMain> BudgetSummaryMain { get; set; }
        public DbSet<BudgetSummaryReport> BudgetSummaryReport { get; set; }
        public DbSet<CarChangeInfo> CarChangeInfo { get; set; }
        public DbSet<CaseKind> CaseKind { get; set; }
        public DbSet<ChequeReason> ChequeReason { get; set; }
        public DbSet<CombindBudget> CombindBudget { get; set; }
        public DbSet<CombindUsageBudget> CombindUsageBudget { get; set; }
        public DbSet<DeductBudget> DeductBudget { get; set; }
        public DbSet<DeductSubjectBudget> DeductSubjectBudget { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<EmployeeSummary> EmployeeSummary { get; set; }
        public DbSet<ExpenseUsage> ExpenseUsage { get; set; }
        public DbSet<FinalAccumulateAdjustMain> FinalAccumulateAdjustMain { get; set; }
        public DbSet<FinalAccumulateAdjustReport> FinalAccumulateAdjustReport { get; set; }
        public DbSet<FinalAccumulateCashFlow_Desc> FinalAccumulateCashFlow_Desc { get; set; }
        public DbSet<FinalAccumulateCertifyMain> FinalAccumulateCertifyMain { get; set; }
        public DbSet<FinalAccumulateCertifyReport> FinalAccumulateCertifyReport { get; set; }
        public DbSet<FinalAccumulateMain> FinalAccumulateMain { get; set; }
        public DbSet<FinalAccumulateReport> FinalAccumulateReport { get; set; }
        public DbSet<FinalCashFlowRecord> FinalCashFlowRecord { get; set; }
        public DbSet<FinalCashFlowRecord_Desc> FinalCashFlowRecord_Desc { get; set; }
        public DbSet<FinalPhaseParam> FinalPhaseParam { get; set; }
        public DbSet<FinalReportCloseRecord> FinalReportCloseRecord { get; set; }
        public DbSet<FinalReportCloseRecord_Adjust> FinalReportCloseRecord_Adjust { get; set; }
        public DbSet<FinalReportCloseRecord_Certify> FinalReportCloseRecord_Certify { get; set; }
        public DbSet<FinalReportDesc> FinalReportDesc { get; set; }
        public DbSet<FinalReportDesc_Adjust> FinalReportDesc_Adjust { get; set; }
        public DbSet<FinalReportDesc_Certify> FinalReportDesc_Certify { get; set; }
        public DbSet<FinalReportRecord> FinalReportRecord { get; set; }
        public DbSet<FinalReportRecord_Adjust> FinalReportRecord_Adjust { get; set; }
        public DbSet<FinalReportRecord_Certify> FinalReportRecord_Certify { get; set; }
        public DbSet<FinalSummaryAdjustMain> FinalSummaryAdjustMain { get; set; }
        public DbSet<FinalSummaryAdjustReport> FinalSummaryAdjustReport { get; set; }
        public DbSet<FinalSummaryCertifyMain> FinalSummaryCertifyMain { get; set; }
        public DbSet<FinalSummaryCertifyReport> FinalSummaryCertifyReport { get; set; }
        public DbSet<FinalSummaryMain> FinalSummaryMain { get; set; }
        public DbSet<FinalSummaryReport> FinalSummaryReport { get; set; }
        public DbSet<FixedItemDetail> FixedItemDetail { get; set; }
        public DbSet<FixedItemMain> FixedItemMain { get; set; }
        public DbSet<FundsInfo> FundsInfo { get; set; }
        public DbSet<GBCJSONRecord> GBCJSONRecord { get; set; }
        public DbSet<GBCRecord> GBCRecord { get; set; }
        public DbSet<GBCVisaDetailAbateDetail> GBCVisaDetailAbateDetail { get; set; }
        public DbSet<HalfYearlyAccumulateMain> HalfYearlyAccumulateMain { get; set; }
        public DbSet<HalfYearlyAccumulateReport> HalfYearlyAccumulateReport { get; set; }
        public DbSet<HalfYearlyReportCloseRecord> HalfYearlyReportCloseRecord { get; set; }
        public DbSet<HalfYearlyReportRecord> HalfYearlyReportRecord { get; set; }
        public DbSet<HalfYearlySummaryMain> HalfYearlySummaryMain { get; set; }
        public DbSet<HalfYearlySummaryReport> HalfYearlySummaryReport { get; set; }
        public DbSet<InOutSubject> InOutSubject { get; set; }
        public DbSet<InvestInfo> InvestInfo { get; set; }
        public DbSet<LoanInfo> LoanInfo { get; set; }
        public DbSet<LongTermDebt> LongTermDebt { get; set; }
        public DbSet<MakeupBudget> MakeupBudget { get; set; }
        public DbSet<MakeupUsageBudget> MakeupUsageBudget { get; set; }
        public DbSet<ManageReportCloseRecord> ManageReportCloseRecord { get; set; }
        public DbSet<ManageReportRecord> ManageReportRecord { get; set; }
        public DbSet<MonthlyAccumulateMain> MonthlyAccumulateMain { get; set; }
        public DbSet<MonthlyAccumulateReport> MonthlyAccumulateReport { get; set; }
        public DbSet<MonthlyReportCloseRecord> MonthlyReportCloseRecord { get; set; }
        public DbSet<MonthlyReportRecord> MonthlyReportRecord { get; set; }
        public DbSet<MonthlySummaryMain> MonthlySummaryMain { get; set; }
        public DbSet<MonthlySummaryReport> MonthlySummaryReport { get; set; }
        public DbSet<NBAABatchDetail> NBAABatchDetail { get; set; }
        public DbSet<NBAABatchRecord> NBAABatchRecord { get; set; }
        public DbSet<PayeeRecord> PayeeRecord { get; set; }
        public DbSet<PayeeType> PayeeType { get; set; }
        public DbSet<PayFeeType> PayFeeType { get; set; }
        public DbSet<PaymentDetail_01> PaymentDetail_01 { get; set; }
        public DbSet<PaymentDetail_02> PaymentDetail_02 { get; set; }
        public DbSet<PaymentDetail_03> PaymentDetail_03 { get; set; }
        public DbSet<PaymentDetail_04> PaymentDetail_04 { get; set; }
        public DbSet<PaymentDetail_05> PaymentDetail_05 { get; set; }
        public DbSet<PaymentDetail_06> PaymentDetail_06 { get; set; }
        public DbSet<PaymentDetail_07> PaymentDetail_07 { get; set; }
        public DbSet<PaymentDetail_08> PaymentDetail_08 { get; set; }
        public DbSet<PaymentDetail_09> PaymentDetail_09 { get; set; }
        public DbSet<PaymentDetail_10> PaymentDetail_10 { get; set; }
        public DbSet<PaymentFeeType> PaymentFeeType { get; set; }
        public DbSet<PaymentRecord_01> PaymentRecord_01 { get; set; }
        public DbSet<PaymentRecord_02> PaymentRecord_02 { get; set; }
        public DbSet<PaymentRecord_03> PaymentRecord_03 { get; set; }
        public DbSet<PaymentRecord_04> PaymentRecord_04 { get; set; }
        public DbSet<PaymentRecord_05> PaymentRecord_05 { get; set; }
        public DbSet<PaymentRecord_06> PaymentRecord_06 { get; set; }
        public DbSet<PaymentRecord_07> PaymentRecord_07 { get; set; }
        public DbSet<PaymentRecord_08> PaymentRecord_08 { get; set; }
        public DbSet<PaymentRecord_09> PaymentRecord_09 { get; set; }
        public DbSet<PaymentRecord_10> PaymentRecord_10 { get; set; }
        public DbSet<PayType> PayType { get; set; }
        public DbSet<PayVoucherBatchDetail> PayVoucherBatchDetail { get; set; }
        public DbSet<PayVoucherBatchRecord> PayVoucherBatchRecord { get; set; }
        public DbSet<PayVoucherParam> PayVoucherParam { get; set; }
        public DbSet<PkindType> PkindType { get; set; }
        public DbSet<PlanExecute> PlanExecute { get; set; }
        public DbSet<PlanUsageType> PlanUsageType { get; set; }
        public DbSet<ProjectPlan> ProjectPlan { get; set; }
        public DbSet<PublicParam> PublicParam { get; set; }
        public DbSet<PUnitRecord_01> PUnitRecord_01 { get; set; }
        public DbSet<PUnitRecord_02> PUnitRecord_02 { get; set; }
        public DbSet<PUnitRecord_03> PUnitRecord_03 { get; set; }
        public DbSet<PUnitRecord_04> PUnitRecord_04 { get; set; }
        public DbSet<PUnitRecord_05> PUnitRecord_05 { get; set; }
        public DbSet<PUnitRecord_06> PUnitRecord_06 { get; set; }
        public DbSet<PUnitRecord_07> PUnitRecord_07 { get; set; }
        public DbSet<PUnitRecord_0701> PUnitRecord_0701 { get; set; }
        public DbSet<PUnitRecord_08> PUnitRecord_08 { get; set; }
        public DbSet<PUnitRecord_10> PUnitRecord_10 { get; set; }
        public DbSet<PurchaseProperty> PurchaseProperty { get; set; }
        public DbSet<Subject> Subject { get; set; }
        public DbSet<SubjectPlan> SubjectPlan { get; set; }
        public DbSet<SubjectPlanUsageType> SubjectPlanUsageType { get; set; }
        public DbSet<SubjectSubRecord> SubjectSubRecord { get; set; }
        public DbSet<SubjectSubType> SubjectSubType { get; set; }
        public DbSet<SummaryFinalReportDesc> SummaryFinalReportDesc { get; set; }
        public DbSet<SysLinkInfo> SysLinkInfo { get; set; }
        public DbSet<TradeItem> TradeItem { get; set; }
        public DbSet<TradeItemDetail> TradeItemDetail { get; set; }
        public DbSet<UsageEmployee> UsageEmployee { get; set; }
        public DbSet<UsageType> UsageType { get; set; }
        public DbSet<UserPwdLog> UserPwdLog { get; set; }
        public DbSet<VouDetail> VouDetail { get; set; }
        public DbSet<VouInvoice> VouInvoice { get; set; }
        public DbSet<VouMain> VouMain { get; set; }
        public DbSet<VouPayee> VouPayee { get; set; }
        public DbSet<VouRecord> VouRecord { get; set; }
        public DbSet<VouSource> VouSource { get; set; }
        public DbSet<YearlyBudget> YearlyBudget { get; set; }
        public DbSet<YearlyOffsetRecord> YearlyOffsetRecord { get; set; }
        public DbSet<YearlyPurchasePropertyEstimation> YearlyPurchasePropertyEstimation { get; set; }
        public DbSet<YearlySubjectBudget> YearlySubjectBudget { get; set; }
        public DbSet<YearlySubjectEstimation> YearlySubjectEstimation { get; set; }
        public DbSet<GBCJSONRecordLog> GBCJSONRecordLog { get; set; }
    }
}
