//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccWebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayVoucherParam
    {
        public string FundNo { get; set; }
        public int OrderNo { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public string AreaCode { get; set; }
        public string Address { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Email { get; set; }
        public string UnifyNo { get; set; }
        public string TaxCode { get; set; }
        public string BudgetSubNo { get; set; }
        public string AccSubNo { get; set; }
        public string BudgetSubName { get; set; }
        public string SPNM { get; set; }
        public string ChargePerson { get; set; }
    }
}
