//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccWebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUnitRecord_06
    {
        public string FundNo { get; set; }
        public int OrderNo { get; set; }
        public string UnifyNo { get; set; }
        public string CityName { get; set; }
        public string TaxUnitCode { get; set; }
        public string TaxUnitName { get; set; }
        public string UnitName { get; set; }
        public string Address { get; set; }
        public string ReputyPerson { get; set; }
    }
}
