//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccWebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsageEmployee
    {
        public string FundNo { get; set; }
        public string AccYear { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public Nullable<long> AccumulateSubjectAmount_11 { get; set; }
        public Nullable<long> AccumulateSubjectAmount_12 { get; set; }
        public Nullable<long> AccumulateSubjectAmount_13 { get; set; }
        public Nullable<long> AccumulateSubjectAmount_14 { get; set; }
        public Nullable<long> AccumulateSubjectAmount_15 { get; set; }
        public Nullable<long> AccumulateSubjectAmount_16 { get; set; }
        public Nullable<long> AccumulateSubjectAmount_17 { get; set; }
        public Nullable<long> AccumulateSubjectAmount_18 { get; set; }
        public Nullable<long> AccumulateSubjectAmount_19 { get; set; }
        public Nullable<long> AccumulateSubjectAmount_20 { get; set; }
        public Nullable<long> AccumulateAmount_11 { get; set; }
        public Nullable<long> AccumulateAmount_12 { get; set; }
        public Nullable<long> AccumulateAmount_13 { get; set; }
        public Nullable<long> AccumulateAmount_14 { get; set; }
        public Nullable<long> AccumulateAmount_15 { get; set; }
        public Nullable<long> AccumulateAmount_16 { get; set; }
        public Nullable<long> AccumulateAmount_17 { get; set; }
        public Nullable<long> AccumulateAmount_18 { get; set; }
        public Nullable<long> AccumulateAmount_19 { get; set; }
        public Nullable<long> AccumulateAmount_20 { get; set; }
    }
}
