//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccWebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VouInvoice
    {
        public string FundNo { get; set; }
        public string AccYear { get; set; }
        public string AccType { get; set; }
        public int AccMainNo { get; set; }
        public int Sno { get; set; }
        public string SheetType { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string UnionNo { get; set; }
        public string CompanyName { get; set; }
        public Nullable<double> InvoiceAmount { get; set; }
    }
}
