//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccWebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearlyOffsetRecord
    {
        public string FundNo { get; set; }
        public string AccYear { get; set; }
        public string AccType { get; set; }
        public string OffsetNo { get; set; }
        public string DC { get; set; }
        public string SubNo { get; set; }
        public string SubName { get; set; }
        public string Memo { get; set; }
        public Nullable<long> Amount { get; set; }
        public string PlanNo { get; set; }
        public string PlanName { get; set; }
        public string PlanSubNo { get; set; }
        public string PlanSubName { get; set; }
        public string UsageNo { get; set; }
        public string UsageName { get; set; }
        public string PkindNo { get; set; }
        public string PkindName { get; set; }
        public string ToWardCode { get; set; }
        public string ToWardDesc { get; set; }
        public string PayeeName { get; set; }
    }
}
