//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccWebService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearlySubjectBudget
    {
        public string FundNo { get; set; }
        public string AccYear { get; set; }
        public string SubNo { get; set; }
        public Nullable<long> YearlySubjectAmount { get; set; }
        public Nullable<long> ReserveSubjectAmount { get; set; }
        public Nullable<long> YearlySubjectAmount_01 { get; set; }
        public Nullable<long> YearlySubjectAmount_02 { get; set; }
        public Nullable<long> YearlySubjectAmount_03 { get; set; }
        public Nullable<long> YearlySubjectAmount_04 { get; set; }
        public Nullable<long> YearlySubjectAmount_05 { get; set; }
        public Nullable<long> YearlySubjectAmount_06 { get; set; }
        public Nullable<long> YearlySubjectAmount_07 { get; set; }
        public Nullable<long> YearlySubjectAmount_08 { get; set; }
        public Nullable<long> YearlySubjectAmount_09 { get; set; }
        public Nullable<long> YearlySubjectAmount_10 { get; set; }
        public Nullable<long> YearlySubjectAmount_11 { get; set; }
        public Nullable<long> YearlySubjectAmount_12 { get; set; }
        public Nullable<long> ReserveSubjectAmount_01 { get; set; }
        public Nullable<long> ReserveSubjectAmount_02 { get; set; }
        public Nullable<long> ReserveSubjectAmount_03 { get; set; }
        public Nullable<long> ReserveSubjectAmount_04 { get; set; }
        public Nullable<long> ReserveSubjectAmount_05 { get; set; }
        public Nullable<long> ReserveSubjectAmount_06 { get; set; }
        public Nullable<long> ReserveSubjectAmount_07 { get; set; }
        public Nullable<long> ReserveSubjectAmount_08 { get; set; }
        public Nullable<long> ReserveSubjectAmount_09 { get; set; }
        public Nullable<long> ReserveSubjectAmount_10 { get; set; }
        public Nullable<long> ReserveSubjectAmount_11 { get; set; }
        public Nullable<long> ReserveSubjectAmount_12 { get; set; }
    }
}
