//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace AccWebService.HPAGBCWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HPAGBCWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class HPAGBCWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAccKindOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSP_GBCVisaDetailJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSP_GBCVisaDetailJSONForVoucherOperationCompleted;
        
        private System.Threading.SendOrPostCallback FillVouNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataExchangeVouMainOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertVouDataFromNPSFOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteVouDataFromNPSFOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HPAGBCWebService() {
            this.Url = global::AccWebService.Properties.Settings.Default.AccWebService_HPAGBCWebService_HPAGBCWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAccKindCompletedEventHandler GetAccKindCompleted;
        
        /// <remarks/>
        public event GetSP_GBCVisaDetailJSONCompletedEventHandler GetSP_GBCVisaDetailJSONCompleted;
        
        /// <remarks/>
        public event GetSP_GBCVisaDetailJSONForVoucherCompletedEventHandler GetSP_GBCVisaDetailJSONForVoucherCompleted;
        
        /// <remarks/>
        public event FillVouNoCompletedEventHandler FillVouNoCompleted;
        
        /// <remarks/>
        public event GetDataExchangeVouMainCompletedEventHandler GetDataExchangeVouMainCompleted;
        
        /// <remarks/>
        public event InsertVouDataFromNPSFCompletedEventHandler InsertVouDataFromNPSFCompleted;
        
        /// <remarks/>
        public event DeleteVouDataFromNPSFCompletedEventHandler DeleteVouDataFromNPSFCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccKind", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAccKind(string AccYear, string BarCode) {
            object[] results = this.Invoke("GetAccKind", new object[] {
                        AccYear,
                        BarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccKindAsync(string AccYear, string BarCode) {
            this.GetAccKindAsync(AccYear, BarCode, null);
        }
        
        /// <remarks/>
        public void GetAccKindAsync(string AccYear, string BarCode, object userState) {
            if ((this.GetAccKindOperationCompleted == null)) {
                this.GetAccKindOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccKindOperationCompleted);
            }
            this.InvokeAsync("GetAccKind", new object[] {
                        AccYear,
                        BarCode}, this.GetAccKindOperationCompleted, userState);
        }
        
        private void OnGetAccKindOperationCompleted(object arg) {
            if ((this.GetAccKindCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccKindCompleted(this, new GetAccKindCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSP_GBCVisaDetailJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSP_GBCVisaDetailJSON(string AccYear, string BarCode, string AccType) {
            object[] results = this.Invoke("GetSP_GBCVisaDetailJSON", new object[] {
                        AccYear,
                        BarCode,
                        AccType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSP_GBCVisaDetailJSONAsync(string AccYear, string BarCode, string AccType) {
            this.GetSP_GBCVisaDetailJSONAsync(AccYear, BarCode, AccType, null);
        }
        
        /// <remarks/>
        public void GetSP_GBCVisaDetailJSONAsync(string AccYear, string BarCode, string AccType, object userState) {
            if ((this.GetSP_GBCVisaDetailJSONOperationCompleted == null)) {
                this.GetSP_GBCVisaDetailJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSP_GBCVisaDetailJSONOperationCompleted);
            }
            this.InvokeAsync("GetSP_GBCVisaDetailJSON", new object[] {
                        AccYear,
                        BarCode,
                        AccType}, this.GetSP_GBCVisaDetailJSONOperationCompleted, userState);
        }
        
        private void OnGetSP_GBCVisaDetailJSONOperationCompleted(object arg) {
            if ((this.GetSP_GBCVisaDetailJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSP_GBCVisaDetailJSONCompleted(this, new GetSP_GBCVisaDetailJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSP_GBCVisaDetailJSONForVoucher", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSP_GBCVisaDetailJSONForVoucher(string AccYear, string BarCode) {
            object[] results = this.Invoke("GetSP_GBCVisaDetailJSONForVoucher", new object[] {
                        AccYear,
                        BarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSP_GBCVisaDetailJSONForVoucherAsync(string AccYear, string BarCode) {
            this.GetSP_GBCVisaDetailJSONForVoucherAsync(AccYear, BarCode, null);
        }
        
        /// <remarks/>
        public void GetSP_GBCVisaDetailJSONForVoucherAsync(string AccYear, string BarCode, object userState) {
            if ((this.GetSP_GBCVisaDetailJSONForVoucherOperationCompleted == null)) {
                this.GetSP_GBCVisaDetailJSONForVoucherOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSP_GBCVisaDetailJSONForVoucherOperationCompleted);
            }
            this.InvokeAsync("GetSP_GBCVisaDetailJSONForVoucher", new object[] {
                        AccYear,
                        BarCode}, this.GetSP_GBCVisaDetailJSONForVoucherOperationCompleted, userState);
        }
        
        private void OnGetSP_GBCVisaDetailJSONForVoucherOperationCompleted(object arg) {
            if ((this.GetSP_GBCVisaDetailJSONForVoucherCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSP_GBCVisaDetailJSONForVoucherCompleted(this, new GetSP_GBCVisaDetailJSONForVoucherCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FillVouNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FillVouNo(string accYear, string acmWordNum, string accKind, string accCount, string accDetail, string vouNo, string vouDate, string passNo, string passDate) {
            object[] results = this.Invoke("FillVouNo", new object[] {
                        accYear,
                        acmWordNum,
                        accKind,
                        accCount,
                        accDetail,
                        vouNo,
                        vouDate,
                        passNo,
                        passDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FillVouNoAsync(string accYear, string acmWordNum, string accKind, string accCount, string accDetail, string vouNo, string vouDate, string passNo, string passDate) {
            this.FillVouNoAsync(accYear, acmWordNum, accKind, accCount, accDetail, vouNo, vouDate, passNo, passDate, null);
        }
        
        /// <remarks/>
        public void FillVouNoAsync(string accYear, string acmWordNum, string accKind, string accCount, string accDetail, string vouNo, string vouDate, string passNo, string passDate, object userState) {
            if ((this.FillVouNoOperationCompleted == null)) {
                this.FillVouNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFillVouNoOperationCompleted);
            }
            this.InvokeAsync("FillVouNo", new object[] {
                        accYear,
                        acmWordNum,
                        accKind,
                        accCount,
                        accDetail,
                        vouNo,
                        vouDate,
                        passNo,
                        passDate}, this.FillVouNoOperationCompleted, userState);
        }
        
        private void OnFillVouNoOperationCompleted(object arg) {
            if ((this.FillVouNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FillVouNoCompleted(this, new FillVouNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataExchangeVouMain", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDataExchangeVouMain(string AccYear, string State, string Memo, System.DateTime StartDate, System.DateTime EndDate) {
            object[] results = this.Invoke("GetDataExchangeVouMain", new object[] {
                        AccYear,
                        State,
                        Memo,
                        StartDate,
                        EndDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataExchangeVouMainAsync(string AccYear, string State, string Memo, System.DateTime StartDate, System.DateTime EndDate) {
            this.GetDataExchangeVouMainAsync(AccYear, State, Memo, StartDate, EndDate, null);
        }
        
        /// <remarks/>
        public void GetDataExchangeVouMainAsync(string AccYear, string State, string Memo, System.DateTime StartDate, System.DateTime EndDate, object userState) {
            if ((this.GetDataExchangeVouMainOperationCompleted == null)) {
                this.GetDataExchangeVouMainOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataExchangeVouMainOperationCompleted);
            }
            this.InvokeAsync("GetDataExchangeVouMain", new object[] {
                        AccYear,
                        State,
                        Memo,
                        StartDate,
                        EndDate}, this.GetDataExchangeVouMainOperationCompleted, userState);
        }
        
        private void OnGetDataExchangeVouMainOperationCompleted(object arg) {
            if ((this.GetDataExchangeVouMainCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataExchangeVouMainCompleted(this, new GetDataExchangeVouMainCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertVouDataFromNPSF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertVouDataFromNPSF(string VouDataJSON) {
            object[] results = this.Invoke("InsertVouDataFromNPSF", new object[] {
                        VouDataJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertVouDataFromNPSFAsync(string VouDataJSON) {
            this.InsertVouDataFromNPSFAsync(VouDataJSON, null);
        }
        
        /// <remarks/>
        public void InsertVouDataFromNPSFAsync(string VouDataJSON, object userState) {
            if ((this.InsertVouDataFromNPSFOperationCompleted == null)) {
                this.InsertVouDataFromNPSFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertVouDataFromNPSFOperationCompleted);
            }
            this.InvokeAsync("InsertVouDataFromNPSF", new object[] {
                        VouDataJSON}, this.InsertVouDataFromNPSFOperationCompleted, userState);
        }
        
        private void OnInsertVouDataFromNPSFOperationCompleted(object arg) {
            if ((this.InsertVouDataFromNPSFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertVouDataFromNPSFCompleted(this, new InsertVouDataFromNPSFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteVouDataFromNPSF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteVouDataFromNPSF(string VouDataJSON) {
            object[] results = this.Invoke("DeleteVouDataFromNPSF", new object[] {
                        VouDataJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteVouDataFromNPSFAsync(string VouDataJSON) {
            this.DeleteVouDataFromNPSFAsync(VouDataJSON, null);
        }
        
        /// <remarks/>
        public void DeleteVouDataFromNPSFAsync(string VouDataJSON, object userState) {
            if ((this.DeleteVouDataFromNPSFOperationCompleted == null)) {
                this.DeleteVouDataFromNPSFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteVouDataFromNPSFOperationCompleted);
            }
            this.InvokeAsync("DeleteVouDataFromNPSF", new object[] {
                        VouDataJSON}, this.DeleteVouDataFromNPSFOperationCompleted, userState);
        }
        
        private void OnDeleteVouDataFromNPSFOperationCompleted(object arg) {
            if ((this.DeleteVouDataFromNPSFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteVouDataFromNPSFCompleted(this, new DeleteVouDataFromNPSFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAccKindCompletedEventHandler(object sender, GetAccKindCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccKindCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccKindCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetSP_GBCVisaDetailJSONCompletedEventHandler(object sender, GetSP_GBCVisaDetailJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSP_GBCVisaDetailJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSP_GBCVisaDetailJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetSP_GBCVisaDetailJSONForVoucherCompletedEventHandler(object sender, GetSP_GBCVisaDetailJSONForVoucherCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSP_GBCVisaDetailJSONForVoucherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSP_GBCVisaDetailJSONForVoucherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FillVouNoCompletedEventHandler(object sender, FillVouNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FillVouNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FillVouNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetDataExchangeVouMainCompletedEventHandler(object sender, GetDataExchangeVouMainCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataExchangeVouMainCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataExchangeVouMainCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void InsertVouDataFromNPSFCompletedEventHandler(object sender, InsertVouDataFromNPSFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertVouDataFromNPSFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertVouDataFromNPSFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeleteVouDataFromNPSFCompletedEventHandler(object sender, DeleteVouDataFromNPSFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteVouDataFromNPSFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteVouDataFromNPSFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591